# https://commitizen-tools.github.io/commitizen/config/
[tool.commitizen]
name = "cz_conventional_commits"
version = "0.1.0"
# git tag format
tag_format = "v$version"
# Useful during the initial development stage of your project. When your project becomes mature,turn if off.
major_version_zero = true
# sync multi version files
version_files = [
    "ch09/first-python-package/src/imppkg/__version__.py",
    "ch09/first-python-package/setup.cfg:version"
]
update_changelog_on_bump = true
# Create custom commit message, useful to skip ci by [skip-ci].
bump_message = "release $current_version → $new_version [skip-ci]"
style = [
    ["qmark", "fg:#ff3617 bold"],
    ["question", "bold"],
    ["answer", "fg:#ff3617 bold"],
    ["pointer", "fg:#ff3617 bold"],
    ["highlighted", "fg:#ff3617 bold"],
    ["selected", "fg:#57cc45"],
    ["separator", "fg:#57cc45"],
    ["instruction", ""],
    ["text", ""],
    ["disabled", "fg:#858585 italic"]
]