repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
      - id: pyupgrade
        args: [ '--py39-plus' ]

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3.10
        files: ^ch09/
        types_or: [ python ]
        # exclude also work
        # exclude: ^(ch10/|other/folder/)
        args: [ '--config=ch09/first-python-package/pyproject.toml' ]  # Just use '--config=pyproject.toml' in your project

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        exclude: ^(ch10/|other/folder/)
        # E303: too much empty lines
        args: [ '--config=ch09/first-python-package/setup.cfg', '--ignore=E303' ]
