[build-system]
requires = ["setuptools", "wheel", "cython"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 120
target-version = ['py39', 'py310']
include = '(ch09\/.*\.pyi?$)|(test\/.*\.pyi?$)'
#exclude = ''''''

